//Fichier de création des jauges 

var g = new JustGage({
      id: "gauge",
      value: 0,
      min: 0,
      max: 100,
      title: "Usage disque dur",
      titleFontColor: "#808080",
      titlePosition: "below",
      valueFontColor: "#808080",
      levelColors: ["#0ce663",
                    "#d1ee0f",
                    "#f62b2b"],
      gaugeColor: "#e2e2e2",
      formatNumber: true,
      label: "Go",
      decimals:true,
      relativeGaugeSize: true,
  });

  var g2 = new JustGage({
      id: "gauge2",
      value: 0,
      min: 0,
      max: 100,
      title: "Utilisation UC",
      titleFontColor: "#808080",
      titlePosition: "below",
      valueFontColor: "#808080",
      levelColors: ["#0ce663",
                    "#d1ee0f",
                    "#f62b2b"],
      gaugeColor: "#e2e2e2",
      label: "%",
      decimals:true,
      relativeGaugeSize: true,
  });
  var g3 = new JustGage({
      id: "gauge3",
      value: 0,
      min: 0,
      max: 4096,
      title: "RAM",
      titleFontColor: "#808080",
      titlePosition: "below",
      valueFontColor: "#808080",
      levelColors: ["#0ce663",
                    "#d1ee0f",
                    "#f62b2b"],
      gaugeColor: "#e2e2e2",
      label: "MB",
      relativeGaugeSize: true,
  });
  var g4 = new JustGage({
      id: "gauge4",
      value: 0,
      min: 0,
      max: 10,
      title: "Load Average",
      titleFontColor: "#808080",
      titlePosition: "below",
      valueFontColor: "#808080",
      levelColors: ["#0ce663",
                    "#d1ee0f",
                    "#f62b2b"],
      gaugeColor: "#e2e2e2",
      formatNumber: true,
      decimals: true,
      relativeGaugeSize: true,
  });
